FROM alpine AS build
WORKDIR /client
COPY package.json .
RUN apk add --update npm
COPY . .
RUN npm ci
RUN npm run build

FROM nginx:alpine
COPY --from=build /client/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]